
trigger:
- develop
-
pool:
  name: 'Azure Pipelines'

variables:
  buildConfiguration: 'Release'
 

stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 6.0.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
    -
    

-