
trigger:
- develop
-
pool:
  name: 'demo'

variables:
  buildConfiguration: 'Release'
 

stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 6.0.x
        installationPath: $(Agent.ToolsDirectory)/dotnet

- stage: 'Deploy to dev'
  variables:
    appName: 'As12'

  jobs:
  - deployment: 'dev'
    environment: 'dev'
    strategy:
       runOnce:
        deploy:
         steps:
           - task: AzureRmWebAppDeployment@4
             inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: 'Azure subscription 1'
                appType: 'webApplinux'
                WebAppName: $(appName)
                SlotName: 'Dev'
                packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'