

trigger:
- develop
- feature/*
- master

pool:
  name: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net6.0'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'

