trigger:
- develop

pool:
 name: 'Azure Pipelines'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: 'sdk'
    version: '6.0.X'
    installationPath: $(Agent.ToolsDirectory)/dotnet

